
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER_ID: 1001
        GROUP_ID: 1001
    container_name: dating_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - composer_cache:/home/www-data/.composer
    depends_on:
      - dating_db
      - redis
    environment:
      - DB_HOST=dating_db
      - DB_DATABASE=dating
      - DB_USERNAME=dating
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - laravel_dating

  nginx:
    image: nginx:alpine
    container_name: dating_nginx
    restart: unless-stopped
    ports:
      - "1111:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_dating

  dating_db:
    image: mysql:8.0
    container_name: dating_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dating
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dating
      MYSQL_PASSWORD: secret
    ports:
      - "3355:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - laravel_dating

  redis:
    image: redis:7-alpine
    container_name: dating_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel_dating

  mailhog:
    image: mailhog/mailhog
    container_name: dating_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel_dating

networks:
  laravel_dating:
    driver: bridge

volumes:
  dbdata:
  redis_data:
  composer_cache:
